### ISSUE TITLE
Circular dependency in nuget package

### ISSUE THREAD

**Issue by toburger** [fsprojects/FSharpx.Extras#322]
When I try to install FSharpx.Extras from nuget I get an error message:

> Circular dependency detected 'FSharpx.Extras 1.10.0 => FSharpx.Extras 1.10.0'.

**Comment by scrwtp** [comment]
Seeing the same thing. The [nuget page][1] actually has the dependency listed.

[1]: http://www.nuget.org/packages/FSharpx.Extras/1.10.0

**Comment by dsyme** [comment]
It looks like this should be fixed in 1.10.2.  If not, please help fix the dependencies listed in build.fsx.  It's possible this should be switched to use Nuget's Paket.Pack, see https://github.com/fsprojects/FSharpx.Async/blob/master/build.fsx#L161, though that may involving moving this repo to use paket more generally (which would also be ok).  

I'm not very familiar with that so if anyone knows how best to grab the implied dependencies just dive in.
